### ISSUE TITLE
Enhance of lua script logging

### ISSUE THREAD

**Issue by theodore86** [haproxytech/haproxy-lua-oauth#37]
Thanks for this great addition, is it possible to have an option (config.debug via env variable) to enable the log messages in the script?  At the moment when HAProxy rejects a request due to invalid issuer/audience etc i cannot determine the root cause of the rejection, at least HAProxy does not provide enough info.

Thank you!

**Comment by NickMRamirez** [comment]
Hi @theodore86 

Because the script has debug messages emitted by default, it just needs HAProxy to log those debug messages. For example, in a Docker environment where I log to `stdout`, in the `global` section of my HAProxy configuration I have this `log` line. The logging level is set to `debug`:

```haproxy
global
  log stdout local0 debug

defaults
  log global
```

Alternatively, the following line does the same thing. It would also capture debug messages because it does not specify a syslog level, and so it captures all messages at every level:

```haproxy
global
  log stdout local0

defaults
  log global
```

To change the syslog level with an environment variable, you could use the following syntax, where the environment variable is surrounded by double-quoted and preceded by a dollar sign. The `presetenv` line is optional. It sets a value for the variable only if it is not already set.

```haproxy
global
  # default to info log messages if not otherwise set
  presetenv LOG_LEVEL info 
  log stdout local0 "$LOG_LEVEL"
```

Then, for example, I can set the `LOG_LEVEL` environment variable when using Docker Compose:

```yaml
version: "3"
services:

  haproxy:
    image: haproxytech/haproxy-ubuntu:2.7
    volumes:
    - "./example/haproxy/haproxy.cfg:/etc/haproxy/haproxy.cfg"
    - "./lib/cors.lua:/etc/haproxy/cors.lua"
    ports:
    - "80:80"
    - "443:443"
    - "8080:8080"
    - "9000:9000"
    environment:
      - LOG_LEVEL=debug
```
